# syntax=docker/dockerfile:experimental

FROM node:hydrogen-alpine3.21

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json .
COPY . .

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]