# Generated by Django 5.1.6 on 2025-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflection',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='reflection',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='is_all_day',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_zone',
        ),
        migrations.AddField(
            model_name='reflection',
            name='mood',
            field=models.IntegerField(choices=[(1, 'Very Sad'), (2, 'Sad'), (3, 'Neutral'), (4, 'Happy'), (5, 'Very Happy')], default=None),
        ),
        migrations.AddField(
            model_name='reflection',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='reflection',
            name='productivity_rating',
            field=models.IntegerField(choices=[(1, 'Very Unproductive'), (2, 'Unproductive'), (3, 'Neutral'), (4, 'Productive'), (5, 'Very Productive')], default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
